name: CI

on: 
  issues:
    types: [opened, edited, deleted, transferred, closed, reopened, assigned, unassigned, labeled, unlabeled]

jobs:
  update-blog:
    name: Update Blog
    runs-on: ubuntu-latest

    steps:
    - name: Dump github context
      env: 
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
